---
deploy-image:
  stage: deploy
  tags:
    - cloud
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE_VERSION: $CI_REGISTRY_IMAGE:$HUGO_VERSION
    IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "$IMAGE_VERSION"
    - >-
      docker build
      --tag "$IMAGE_VERSION"
      --tag "$IMAGE_LATEST"
      --build-arg HUGO_VERSION=$HUGO_VERSION
      .
    - docker push "$IMAGE_VERSION"
    - docker push "$IMAGE_LATEST"
